### ISSUE TITLE
Inconsistency between repo and website

### ISSUE THREAD

**Issue by kwiva** [jxnblk/palx#13] opened 2018-09-07 14:38 UTC
It seems that the shade colors generated on palx.jxnblk.com are different than the colors generated with the JavaScript module.

1. Shades are slightly different
1. The website includes the base color as one of the shades

**Comment by wirtzdan** [comment] 2019-02-14 20:02
I'm having the same issue. I'm getting two different color shades from the website and the module, when I input the same color (#2C4CE8)

From the module: 
`"indigo": [
0: "#f8f9fe"
1: "#e9edfd"
2: "#dae0fb"
3: "#c9d1f9"
4: "#b6c2f7"
5: "#a0b0f5"
6: "#889bf2"
7: "#6981ef"
8: "#3f5eea"
9: "#1d3499"
]`

From the website, with the same color: 
`
  "indigo": [
    "#e9edfc",
    "#d2d9fa",
    "#b7c3f7",
    "#97a8f3",
    "#6e85ef",
    "#2c4ee8",
    "#2746d0",
    "#223db6",
    "#1c3295",
    "#132368"
  ]
`

Is this going to be fixed, or is there a alternative to Palx you can recommend?

**Comment by jxnblk** [comment] 2019-02-18 17:25
Duplicate of #11

**Closed by jxnblk** 2019-02-18 17:25 UTC
